const ExcelJS = require('exceljs');
const fs = require('fs');
const path = require('path');
const config = require('../config');
const logger = require('../utils/logger');

class ExcelService {
  constructor() {
    this.reportDir = path.join(config.UPLOAD_DIR, 'reports');
    if (!fs.existsSync(this.reportDir)) {
      fs.mkdirSync(this.reportDir, { recursive: true });
    }
  }

  async generateReportExcel(data, reportId) {
    const filename = `report-${reportId}-${Date.now()}.xlsx`;
    const filepath = path.join(this.reportDir, filename);

    try {
      const workbook = new ExcelJS.Workbook();
      workbook.creator = 'BioDigital BSF';
      workbook.created = new Date();

      const sheet = workbook.addWorksheet('Report');

      // Header style
      const headerFill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2E7D32' } };
      const headerFont = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };

      if (data.title) {
        sheet.mergeCells('A1:D1');
        const titleCell = sheet.getCell('A1');
        titleCell.value = data.title;
        titleCell.font = { bold: true, size: 14 };
        titleCell.alignment = { horizontal: 'center' };
        sheet.addRow([]);
      }

      if (data.records && data.records.length > 0) {
        const columns = [
          { header: 'Date', key: 'date', width: 15 },
          { header: 'Source Name', key: 'sourceName', width: 25 },
          { header: 'Source Type', key: 'sourceType', width: 20 },
          { header: 'Quantity', key: 'quantity', width: 12 },
          { header: 'Unit', key: 'unit', width: 10 },
          { header: 'Status', key: 'status', width: 15 },
          { header: 'Carbon Saved (kg CO2e)', key: 'carbonSaved', width: 22 }
        ];
        sheet.columns = columns;

        const headerRow = sheet.getRow(sheet.rowCount);
        headerRow.eachCell(cell => {
          cell.fill = headerFill;
          cell.font = headerFont;
        });

        data.records.forEach(record => {
          sheet.addRow({
            date: new Date(record.date).toLocaleDateString(),
            sourceName: record.sourceName,
            sourceType: record.sourceType,
            quantity: record.quantity,
            unit: record.unit,
            status: record.status,
            carbonSaved: record.carbonSaved || 0
          });
        });
      } else if (data.summary) {
        sheet.columns = [
          { header: 'Metric', key: 'metric', width: 35 },
          { header: 'Value', key: 'value', width: 25 }
        ];

        const headerRow = sheet.getRow(sheet.rowCount);
        headerRow.eachCell(cell => {
          cell.fill = headerFill;
          cell.font = headerFont;
        });

        sheet.addRow({ metric: 'Total Waste', value: `${data.summary.totalWaste || 0} kg` });
        sheet.addRow({ metric: 'Total Carbon Saved', value: `${data.summary.totalCarbonSaved || 0} kg CO2e` });
        sheet.addRow({ metric: 'Total Records', value: data.summary.totalRecords || 0 });

        if (data.summary.bySourceType) {
          data.summary.bySourceType.forEach(item => {
            sheet.addRow({ metric: `Waste - ${item.sourceType}`, value: `${item._sum.quantity || 0} kg` });
          });
        }
      } else {
        // Generic key-value dump for other report types
        sheet.columns = [
          { header: 'Metric', key: 'metric', width: 35 },
          { header: 'Value', key: 'value', width: 40 }
        ];

        const headerRow = sheet.getRow(sheet.rowCount);
        headerRow.eachCell(cell => {
          cell.fill = headerFill;
          cell.font = headerFont;
        });

        const addRows = (obj, prefix = '') => {
          for (const [key, val] of Object.entries(obj)) {
            if (val === null || val === undefined) continue;
            if (typeof val === 'object' && !Array.isArray(val) && !(val instanceof Date)) {
              addRows(val, prefix ? `${prefix}.${key}` : key);
            } else {
              sheet.addRow({
                metric: prefix ? `${prefix}.${key}` : key,
                value: Array.isArray(val) ? `[${val.length} items]` : String(val)
              });
            }
          }
        };

        const { title: _t, generatedAt, generatedBy, ...rest } = data;
        if (generatedAt) sheet.addRow({ metric: 'Generated At', value: generatedAt });
        if (generatedBy) sheet.addRow({ metric: 'Generated By', value: generatedBy });
        addRows(rest);
      }

      await workbook.xlsx.writeFile(filepath);

      return `/uploads/reports/${filename}`;
    } catch (error) {
      logger.error('Excel generation error:', error);
      throw error;
    }
  }
}

const excelServiceInstance = new ExcelService();

const generateExcel = (data, reportId) => excelServiceInstance.generateReportExcel(data, reportId);

module.exports = { generateExcel, ExcelService };
