const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const config = require('../config');
const logger = require('../utils/logger');

class PDFService {
  constructor() {
    this.reportDir = path.join(config.UPLOAD_DIR, 'reports');
    if (!fs.existsSync(this.reportDir)) {
      fs.mkdirSync(this.reportDir, { recursive: true });
    }
  }

  async generateReportPDF(data, reportId) {
    return new Promise((resolve, reject) => {
      try {
        const filename = `report-${reportId}-${Date.now()}.pdf`;
        const filepath = path.join(this.reportDir, filename);
        
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const stream = fs.createWriteStream(filepath);
        
        doc.pipe(stream);
        
        // Header
        doc.fontSize(20).text(data.title, { align: 'center' });
        doc.moveDown();
        doc.fontSize(10).text(`Generated: ${new Date(data.generatedAt).toLocaleString()}`, { align: 'center' });
        doc.fontSize(10).text(`Generated by: ${data.generatedBy}`, { align: 'center' });
        doc.moveDown();
        doc.lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();
        
        // Summary section
        if (data.summary) {
          doc.fontSize(14).text('Summary', { underline: true });
          doc.moveDown(0.5);
          
          const summaryItems = [
            `Total Waste: ${data.summary.totalWaste || 0} kg`,
            `Total Carbon Saved: ${data.summary.totalCarbonSaved || 0} kg CO2e`,
            `Total Records: ${data.summary.totalRecords || 0}`
          ];
          
          summaryItems.forEach(item => {
            doc.fontSize(10).text(`• ${item}`);
          });
          doc.moveDown();
          
          // By Source Type table
          if (data.summary.bySourceType && data.summary.bySourceType.length > 0) {
            doc.fontSize(12).text('Waste by Source Type');
            doc.moveDown(0.5);
            
            const tableTop = doc.y;
            doc.fontSize(10);
            
            doc.text('Source Type', 50, tableTop);
            doc.text('Quantity (kg)', 250, tableTop);
            doc.text('Records', 400, tableTop);
            
            doc.lineWidth(0.5).moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();
            
            let y = tableTop + 25;
            data.summary.bySourceType.forEach(item => {
              doc.text(item.sourceType, 50, y);
              doc.text((item._sum.quantity || 0).toFixed(2), 250, y);
              doc.text(item._count.toString(), 400, y);
              y += 20;
              
              if (y > 700) {
                doc.addPage();
                y = 50;
              }
            });
            
            doc.moveDown();
          }
        }
        
        // Records section
        if (data.records && data.records.length > 0) {
          doc.addPage();
          doc.fontSize(14).text('Detailed Records', { underline: true });
          doc.moveDown(0.5);
          
          const headers = ['Date', 'Source', 'Type', 'Quantity', 'Status'];
          const columnWidths = [80, 120, 100, 80, 80];
          let x = 50;
          
          doc.fontSize(9);
          headers.forEach((header, i) => {
            doc.text(header, x, doc.y);
            x += columnWidths[i];
          });
          
          doc.lineWidth(0.5).moveTo(50, doc.y + 5).lineTo(550, doc.y + 5).stroke();
          doc.moveDown();
          
          let y = doc.y;
          for (const record of data.records.slice(0, 50)) {
            x = 50;
            doc.text(new Date(record.date).toLocaleDateString(), x, y);
            x += columnWidths[0];
            doc.text(record.sourceName?.substring(0, 20) || '-', x, y);
            x += columnWidths[1];
            doc.text(record.sourceType?.substring(0, 15) || '-', x, y);
            x += columnWidths[2];
            doc.text(`${record.quantity || 0} ${record.unit || 'kg'}`, x, y);
            x += columnWidths[3];
            doc.text(record.status || '-', x, y);
            
            y += 20;
            
            if (y > 750) {
              doc.addPage();
              y = 50;
            }
          }
        }
        
        // Footer
        const totalPages = doc.bufferedPageRange().count;
        for (let i = 0; i < totalPages; i++) {
          doc.switchToPage(i);
          doc.fontSize(8).text(
            `Page ${i + 1} of ${totalPages}`,
            50,
            doc.page.height - 50,
            { align: 'center' }
          );
        }
        
        doc.end();
        
        stream.on('finish', () => {
          const fileUrl = `/uploads/reports/${filename}`;
          resolve(fileUrl);
        });
        
        stream.on('error', reject);
      } catch (error) {
        logger.error('PDF generation error:', error);
        reject(error);
      }
    });
  }

  async generateInvoicePDF(order, invoice) {
    return new Promise((resolve, reject) => {
      try {
        const filename = `invoice-${invoice.invoiceNumber}-${Date.now()}.pdf`;
        const filepath = path.join(this.reportDir, filename);
        
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const stream = fs.createWriteStream(filepath);
        
        doc.pipe(stream);
        
        // Invoice header
        doc.fontSize(24).text('INVOICE', { align: 'center' });
        doc.moveDown();
        
        doc.fontSize(10);
        doc.text(`Invoice Number: ${invoice.invoiceNumber}`, 50, doc.y);
        doc.text(`Invoice Date: ${new Date(invoice.issueDate).toLocaleDateString()}`, 50, doc.y);
        doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 50, doc.y);
        doc.moveDown();
        
        // Company and customer info
        doc.fontSize(12).text('Bill To:', 50, doc.y);
        doc.fontSize(10);
        doc.text(order.customer?.fullName || 'Customer', 50, doc.y);
        if (order.deliveryAddress) {
          doc.text(order.deliveryAddress.street || '', 50, doc.y);
          doc.text(`${order.deliveryAddress.city || ''} ${order.deliveryAddress.region || ''}`, 50, doc.y);
          doc.text(order.deliveryAddress.country || '', 50, doc.y);
        }
        doc.moveDown();
        
        // Order items table
        doc.fontSize(12).text('Order Items', { underline: true });
        doc.moveDown(0.5);
        
        const tableTop = doc.y;
        doc.fontSize(10);
        
        doc.text('Item', 50, tableTop);
        doc.text('Quantity', 300, tableTop);
        doc.text('Unit Price', 400, tableTop);
        doc.text('Total', 480, tableTop);
        
        doc.lineWidth(0.5).moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();
        
        let y = tableTop + 25;
        if (order.items) {
          for (const item of order.items) {
            doc.text(item.variant?.product?.name || 'Product', 50, y);
            doc.text(item.quantity.toString(), 300, y);
            doc.text(`$${item.price.toFixed(2)}`, 400, y);
            doc.text(`$${item.subtotal.toFixed(2)}`, 480, y);
            y += 20;
          }
        }
        
        y += 10;
        doc.lineWidth(0.5).moveTo(50, y).lineTo(550, y).stroke();
        y += 10;
        
        doc.text(`Subtotal:`, 400, y);
        doc.text(`$${order.subtotal?.toFixed(2) || '0.00'}`, 480, y);
        y += 20;
        doc.text(`Shipping:`, 400, y);
        doc.text(`$${order.shippingCost?.toFixed(2) || '0.00'}`, 480, y);
        y += 20;
        doc.text(`Tax:`, 400, y);
        doc.text(`$${order.tax?.toFixed(2) || '0.00'}`, 480, y);
        y += 20;
        
        doc.fontSize(12);
        doc.text(`Total:`, 400, y);
        doc.text(`$${order.total?.toFixed(2) || '0.00'}`, 480, y);
        
        // Footer
        doc.fontSize(8);
        doc.text('Thank you for your business!', 50, doc.page.height - 50, { align: 'center' });
        
        doc.end();
        
        stream.on('finish', () => {
          const fileUrl = `/uploads/reports/${filename}`;
          resolve(fileUrl);
        });
        
        stream.on('error', reject);
      } catch (error) {
        logger.error('Invoice PDF generation error:', error);
        reject(error);
      }
    });
  }
}

module.exports = new PDFService();